[package]
name = "rs-check-horaire"
version = "0.1.0"
authors = ["Christian FOUCHER <christian.foucher@gmail.com>"]

[dependencies]
chrono = "0.4"
horaire = { git = "https://github.com/prisme60/rs-horaire.git" }
sms_freemobile_api = { git = "https://github.com/prisme60/rs-sms-freemobile-api.git"}
